import { useState } from 'react';
import { canAccessPromptStudio } from '../lib/access';
import { AIF_MODULES, HOW_TO_MODULES, effectiveConfig, mapLegacyAccess, type MemberAccessConfig } from '../lib/memberAccessConfig';
export { mapLegacyAccess };
export type LocalAccessConfig = MemberAccessConfig;
const initialExample: MemberAccessConfig = { tiers: ['AIF How To'], aif: [], howTo: ['Thinking With Claude'], sinadRole: 'Student', role: 'member', expiry: '', portals: ['aif'] };
const optionClass = 'flex items-center gap-3 min-h-12 rounded-lg border border-[#001E3C]/15 bg-white px-4 py-3 font-body text-sm text-[#001E3C]';
const inputClass = 'block w-full h-11 mt-2 rounded-lg border border-[#001E3C]/20 px-3 bg-white font-body text-sm text-[#001E3C] focus:outline-none focus:ring-2 focus:ring-[#00AACC]';
export default function MemberAccessPreview({ initial = initialExample, name = 'Member Contoh', email = 'contoh@example.com', onSave, onCancel, persistence = 'preview', disabled = false }: { initial?: MemberAccessConfig; name?: string; email?: string; onSave?: (config: MemberAccessConfig) => void | Promise<void>; onCancel?: () => void; persistence?: 'preview' | 'server' | 'form'; disabled?: boolean }) {
  const [config, setConfig] = useState(initial);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [saved, setSaved] = useState(false);
  const effective = effectiveConfig(config);
  const internal = effective.tiers.includes('Internal');
  const automaticStrategize = effective.howTo.length > 0 && !internal;
  const update = (next: Partial<MemberAccessConfig>) => { setConfig(prev => ({ ...prev, ...next })); setSaved(false); setError(''); };
  const toggle = (key: 'tiers' | 'aif' | 'howTo' | 'portals', value: string) => update({ [key]: config[key].includes(value) ? config[key].filter(v => v !== value) : [...config[key], value] });
  const save = async () => {
    setBusy(true); setError('');
    try { await onSave?.(effective); setSaved(true); }
    catch (err) { setError(err instanceof Error ? err.message : typeof err === 'object' && err && 'message' in err ? String(err.message) : 'Gagal menyimpan. Pilihan belum tersimpan.'); }
    finally { setBusy(false); }
  };
  const studio = canAccessPromptStudio('', effective);
  return <section className="flex h-full min-h-0 flex-col bg-white text-[#001E3C]">
    <header className="shrink-0 border-b border-[#001E3C]/10 px-5 sm:px-7 py-5 flex items-start justify-between gap-4"><div className="min-w-0"><h2 className="font-sans text-xl sm:text-2xl font-bold">Atur Tier</h2><p className="font-body text-sm text-[#6A6A6A] mt-2 break-words">{name}</p><p className="font-body text-xs text-[#6A6A6A] mt-1 break-all">{email}</p></div>{onCancel && <button type="button" disabled={busy} onClick={onCancel} aria-label="Tutup pengaturan tier" className="shrink-0 w-9 h-9 rounded-lg border border-[#001E3C]/15 text-2xl leading-none">×</button>}</header>
    <fieldset disabled={disabled || busy} className="min-h-0 min-w-0 flex-1 overflow-y-auto px-5 sm:px-7 py-6 space-y-6">
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><label className="font-body text-sm font-bold">Role akun<select value={config.role} onChange={e => update({ role: e.target.value })} className={inputClass}><option value="member">Member</option><option value="admin">Admin</option></select></label><label className="font-body text-sm font-bold">Berlaku sampai<input type="date" value={config.expiry} onChange={e => update({ expiry: e.target.value })} className={inputClass} /><span className="block text-xs font-normal text-[#6A6A6A] mt-2">Hingga akhir tanggal (WIB). Kosong untuk tanpa batas.</span></label></div>
      <fieldset><legend className="font-sans text-sm font-bold mb-3">Akses Portal</legend><div className="grid grid-cols-1 sm:grid-cols-3 gap-3">{[{ id: 'aif', title: 'AI First' }, { id: 'idl', title: 'IDL' }, { id: 'sinad', title: 'SinaD' }].map(p => <label key={p.id} className={optionClass}><input type="checkbox" className="w-4 h-4 accent-[#001E3C] shrink-0" checked={effective.portals.includes(p.id)} disabled={internal} onChange={() => toggle('portals', p.id)} /><span>{p.title}</span></label>)}</div><p className="font-body text-xs text-[#6A6A6A] mt-3">Shortcut IDL tersedia untuk semua tier di portal AIF.</p></fieldset>
      <fieldset><legend className="font-sans text-sm font-bold mb-2">Tier</legend><p className="font-body text-xs text-[#6A6A6A] mb-3">Bisa pilih lebih dari satu. Aktifkan portalnya dahulu.</p><div className="grid grid-cols-2 sm:grid-cols-4 gap-3">{['AIF', 'AIF How To', 'Internal', 'SinaD'].map(t => { const blocked = internal && t !== 'Internal' || ['AIF', 'AIF How To'].includes(t) && !effective.portals.includes('aif') || t === 'SinaD' && !effective.portals.includes('sinad'); return <label key={t} className={optionClass + (effective.tiers.includes(t) ? ' !border-[#001E3C] !bg-[#F7F9FC]' : '') + (blocked ? ' opacity-50' : '')}><input type="checkbox" checked={effective.tiers.includes(t)} disabled={blocked} onChange={() => toggle('tiers', t)} className="w-4 h-4 accent-[#001E3C] shrink-0" /><span className="font-bold">{t}</span></label>; })}</div></fieldset>
      {internal && <div className="rounded-xl bg-[#001E3C] text-[#F7F9FC] p-5"><h3 className="font-sans text-sm font-bold">Internal · Semua akses</h3><p className="font-body text-sm mt-2">Semua kotak AIF, AIF How To, serta portal AI First, IDL, dan SinaD. Role akun tetap terpisah.</p></div>}
      {!internal && effective.tiers.includes('AIF') && <fieldset className="rounded-xl border border-[#FCB528]/70 p-4 sm:p-5"><legend className="font-sans text-sm font-bold px-2">Kotak AIF</legend><div className="grid grid-cols-1 sm:grid-cols-2 gap-3">{AIF_MODULES.map(m => <label key={m} className={optionClass}><input type="checkbox" checked={effective.aif.includes(m)} disabled={m === 'Strategize' && automaticStrategize} onChange={() => toggle('aif', m)} className="w-4 h-4 accent-[#001E3C] shrink-0" /><span>{m}{m === 'Strategize' && automaticStrategize && <span className="block text-xs text-[#005287] mt-1">Akses dasar otomatis</span>}</span></label>)}</div></fieldset>}
      {!internal && effective.tiers.includes('AIF How To') && <fieldset className="rounded-xl border border-[#00AACC]/60 p-4 sm:p-5"><legend className="font-sans text-sm font-bold px-2">Kotak AIF How To</legend><p className="font-body text-xs text-[#6A6A6A] mb-3">Strategize otomatis diberikan ketika salah satu kotak dipilih.</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-3">{HOW_TO_MODULES.map(m => <label key={m} className={optionClass}><input type="checkbox" checked={effective.howTo.includes(m)} onChange={() => toggle('howTo', m)} className="w-4 h-4 accent-[#001E3C] shrink-0" /><span>{m}{m === 'Selling Idea With AI' && <span className="block text-xs text-[#6A6A6A] mt-1">Materi belum tersedia</span>}</span></label>)}</div></fieldset>}
      {!internal && effective.tiers.includes('SinaD') && <fieldset className="rounded-xl border border-[#001E3C]/15 p-4 sm:p-5"><legend className="font-sans text-sm font-bold px-2">SinaD</legend><label className="font-body text-sm">Peran di SinaD<select value={config.sinadRole} onChange={e => update({ sinadRole: e.target.value })} className={inputClass}><option>Student</option><option>Teacher</option></select></label>{config.sinadRole === 'Student' && <div className="grid sm:grid-cols-2 gap-3 mt-4"><label className={optionClass}><input type="checkbox" checked={!!config.sinadMateri} onChange={e => update({ sinadMateri: e.target.checked })} />Materi SinaD</label><label className={optionClass}><input type="checkbox" checked={!!config.sinadExercise} onChange={e => update({ sinadExercise: e.target.checked })} />Latihan SinaD</label></div>}</fieldset>}
      <div className="rounded-xl bg-[#F7F9FC] p-4 sm:p-5" aria-live="polite"><h3 className="font-sans text-sm font-bold">Ringkasan akses</h3><p className="font-body text-sm text-[#005287] mt-2">Portal: {effective.portals.map(p => p === 'aif' ? 'AI First' : p === 'idl' ? 'IDL' : 'SinaD').join(' · ') || 'Belum dipilih'}</p><div className="flex flex-wrap gap-2 mt-3">{[...effective.aif, ...effective.howTo].map(m => <span key={m} className="rounded-md border border-[#001E3C]/10 bg-white px-2.5 py-1 font-body text-xs">{m}{m === 'Strategize' && automaticStrategize ? ' · otomatis' : ''}</span>)}{effective.tiers.includes('SinaD') && <span className="font-body text-xs rounded-md bg-white px-2.5 py-1">SinaD · {config.sinadRole}</span>}</div><p className="font-body text-sm font-bold mt-4 pt-3 border-t border-[#001E3C]/10">Prompt Studio: {studio ? 'Diberikan' : 'Tidak diberikan'}</p></div>
    </fieldset>
    <footer className="shrink-0 border-t border-[#001E3C]/10 bg-white px-5 sm:px-7 py-4"><p className="font-body text-xs text-[#6A6A6A] mb-3" role="status">{persistence === 'server' ? 'Simpan untuk memperbarui akses akun di database.' : persistence === 'form' ? 'Pilihan disimpan saat member baru ditambahkan.' : saved ? 'Contoh tersimpan selama halaman terbuka.' : 'Pratinjau dengan data contoh.'}</p>{error && <p role="alert" className="font-body text-sm text-red-700 mb-3">{error}</p>}<div className="flex justify-end gap-3">{onCancel && <button type="button" disabled={busy} onClick={onCancel} className="rounded-lg border border-[#001E3C]/20 font-body font-bold text-sm px-5 py-2.5">Batal</button>}<button type="button" disabled={busy || disabled} onClick={() => void save()} className="rounded-lg bg-[#001E3C] text-[#F7F9FC] font-body font-bold text-sm px-5 py-2.5 disabled:opacity-50 focus-visible:outline-2 focus-visible:outline-[#00AACC]">{busy ? 'Menyimpan…' : persistence === 'server' ? 'Simpan ke database' : persistence === 'form' ? 'Gunakan pilihan' : 'Simpan contoh'}</button></div></footer>
  </section>;
}
